[profile.default]
retries = 0
status-level = "pass"
failure-output = "immediate-final"
success-output = "never"
slow-timeout = { period = "30s", terminate-after = 2 }

[profile.ci]
inherits = "default"
fail-fast = false
